
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebsiteMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class GiaDien
{

    public int IDGiaDien { get; set; }

    public int IDHouse { get; set; }

    public int IDTaiKhoan { get; set; }

    public Nullable<decimal> GiaTien { get; set; }

    public Nullable<System.DateTime> NgayTinh { get; set; }



    public virtual House House { get; set; }

    public virtual TaiKhoan TaiKhoan { get; set; }

}

}
